// Code generated by mockery v2.40.3. DO NOT EDIT.

package mocks

import (
	context "context"
	account "stori-card-challenge-account/domain/account"

	mock "github.com/stretchr/testify/mock"
)

// AccountDBRepository is an autogenerated mock type for the AccountDBRepository type
type AccountDBRepository struct {
	mock.Mock
}

// SaveUserAccount provides a mock function with given fields: ctx, a
func (_m *AccountDBRepository) SaveUserAccount(ctx context.Context, a *account.Account) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for SaveUserAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *account.Account) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccountDBRepository creates a new instance of AccountDBRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountDBRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountDBRepository {
	mock := &AccountDBRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
